### ISSUE TITLE
Error al subir archivos

### ISSUE THREAD

**Issue by javivigu** [GeographicaGS/moocng#92]
En hub8 desde teacheradmin no se pueden subir un fichero a una píldora creada como por ejemplo el fichero [all_the_things_you_are.pdf](https://github.com/GeographicaGS/moocng/files/322821/all_the_things_you_are.pdf) en material complementario de la píldora:

https://hub8.ecolearning.eu/course/ensenando-en-digital-mas-alla-de-la-tecnologia/teacheradmin/units/#kq667

Tarda un ratito y al final aparece el mensaje en rojo superior derecho:

Error
Algo ha ido mal, por favor pruebe de nuevo más tarde.

Lo mismo sucede si quieres subir subtítulos a un vídeo accesible.

**Comment by neokore** [comment]
Ha sido un error de la cola de Celeryd que no conectaba con RabbitMQ. Solucionado.
