### ISSUE TITLE
Dar acceso a descargar certificado en cursos en estado siempre abierto 

### ISSUE THREAD

**Issue by javivigu** [GeographicaGS/moocng#93]
Ahora mismo el contenido del bloque donde aparece la barra amarilla de progreso, el número de tareas realizadas/total y el icono de certificado con su enlace a progress, se oculta cuando el curso está en estado siempre abierto.

Es necesario dar acceso al enlace al certificado - ya sea descarga del pdf o enlace a la aplicación externa de gestión de certificados de la UNED - cuando el alumno haya conseguido pasar el umbral para ello, cuando el curso estaba en estado publicado.

Podría situarse el icono del certificado en el perfil tal como aparece la lista de medallas por ejemplo.

Lo pongo como enhancement aunque podría verse como un bug de usabilidad a mi entender.

**Comment by neokore** [comment]
@javivigu Ya está en producción y he probado un poco con un curso que tenía certificado. Está Ok.
Cierra la tarea cuando confirmes el caso de uso de Sara
